# -*- coding: utf-8 -*-
# @Time    : 2019/5/12 10:14
# @Author  : zhengjiani
# @Software: PyCharm
# @Blog    ：https://zhengjiani.github.io/
from graphviz import Digraph
dot = Digraph(comment='POT Tree')
dot.node('A','LoginPage')
dot.node('M','LoginPage',color='gray',style = 'filled')
dot.node('B','HomePage')
dot.node('O','HomePage',color='gray',style = 'filled')
dot.node('C','AdminPage')
dot.node('N','AdminPage')
dot.node('D','UserPage')
dot.node('Q','UserPage')
dot.node('q','UserListPage',color='gray',style = 'filled')
dot.node('E','UserListPage')
dot.node('F','GoodPage')
dot.node('G','GoodListPage')
dot.node('T','GoodListPage')
dot.node('U','GoodListPage')
dot.node('H','CreatePage')
dot.node('J','ModifyPasswdPage')
dot.node('L','BrandListPage')
dot.node('K','BrandPage')
dot.node('R','BrandPage')
dot.node('S','BrandListPage',color='gray',style = 'filled')
dot.edge('A','B','login()',color='red',penwidth='3.0')
dot.edge('B','M','logout()',color='red',penwidth='3.0')
dot.edge('B','D','goto_user()')
dot.edge('D','Q','add_user()')
dot.edge('Q','q','search_user()')
dot.edge('D','E','search_user()')
dot.edge('B','F','goto_good()')
dot.edge('F','H','add_good()')
dot.edge('H','G','search_good()')
dot.edge('G','T','edit_good()')
dot.edge('G','U','delete_good()')
dot.edge('B','J','goto_passwd()')
dot.edge('B','C','goto_admin()')
dot.edge('C','N','add_admin()')
dot.edge('B','K','goto_brand()')
dot.edge('K','L','search_brand()')
dot.edge('K','R','add_brand()')
dot.edge('R','S','search_brand()')
dot.edge('N','O','back_login()')
print(dot.source)
